name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v20.11.1/bin
          cd ${{ secrets.PROJECT_PATH }}
          git pull origin main
          npm install --production
          pm2 reload ecosystem.config.js --env production
